services:
  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/.devcontainer/Dockerfile
    command: sleep infinity
    ports:
      - 3000:3000
    volumes:
      - .:/grocery-store

  api-gateway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./services/api-gateway/.devcontainer/Dockerfile
    # command: npm run dev
    command: sleep infinity
    depends_on:
      - customer-service
    ports:
      - 4000:4000
    volumes:
      - .:/grocery-store

  customer-service:
    build:
      context: .
      dockerfile: ./services/customer-service/Dockerfile
    command: go run cmd/server/main.go
    # command: sleep infinity
    depends_on:
      - customer-service-db
    env_file:
      - ./services/customer-service/.env
    volumes:
      - .:/grocery-store

  customer-service-db:
    image: mysql:8-oracle
    env_file:
      - ./services/customer-service/.env
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - customer-service-db-data:/var/lib/mysql

volumes:
  customer-service-db-data:
