services:
  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/.devcontainer/Dockerfile
    # command: sleep infinity
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/grocery-store

  api-gateway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./services/api-gateway/.devcontainer/Dockerfile
    command: npm run dev
    # command: sleep infinity
    depends_on:
      - customer-service
    env_file:
      - ./services/.env
    ports:
      - 4000:4000
    volumes:
      - .:/grocery-store

  customer-service:
    build:
      context: .
      dockerfile: ./services/customer-service/Dockerfile
    command: go run cmd/server/main.go
    # command: sleep infinity
    depends_on:
      - customer-service-db
    env_file:
      - ./services/customer-service/.env
    volumes:
      - .:/grocery-store

  customer-service-db:
    image: mysql:8-oracle
    env_file:
      - ./services/customer-service/.env
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - 33061:3306
    volumes:
      - customer-service-db-data:/var/lib/mysql

  grocery-service:
    build:
      context: .
      dockerfile: ./services/grocery-service/Dockerfile
    # command: sleep infinity
    command: cargo run --bin helloworld-server
    depends_on:
      - grocery-service-db
    env_file:
      - ./services/grocery-service/.env
    ports:
      - 50052:50051
    volumes:
      - .:/grocery-store

  grocery-service-db:
    image: mysql:8-oracle
    env_file:
      - ./services/grocery-service/.env
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - 33062:3306
    volumes:
      - grocery-service-db-data:/var/lib/mysql

volumes:
  customer-service-db-data:
  grocery-service-db-data:
