services:
  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    command: go run server.go -port 8080
    ports:
      - 8080:8080
    volumes:
      - .:/ec
