services:
  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/.devcontainer/Dockerfile
    command: sleep infinity
    ports:
      - 3000:3000
    volumes:
      - .:/grocery-store

  customer-service:
    build:
      context: .
      dockerfile: ./services/customer-service/Dockerfile
    command: go run server.go -port 8080
    ports:
      - 8080:8080
    volumes:
      - .:/grocery-store
